#!/bin/sh

mkdir -p build \
  && cd build \
  && rm -rf ./* 2> /dev/null \
  && yarn add livescript \
  && yarn lsc -o . -c ../src/*.ls \
  && yarn lsc -o ./task -c ../src/task/*.ls \
  && yarn install \
  && yarn run build
