#!/bin/sh

mkdir -p build \
  && cd build \
  && rm -rf ./* 2> /dev/null \
  && yarn add livescript \
  && yarn lsc --debug -o . -c ../src/*.ls \
  && yarn lsc --debug -o ./task -c ../src/task/*.ls \
  && yarn lsc --debug -o ./task/yarn -c ../src/task/yarn/*.ls \
  && yarn \
  && yarn run build
