[build]
publish = "build/site"
command = "./bootstrap"

[[plugins]]
package = "@netlify/plugin-sitemap"

# submit sitemap must run after generate sitemap
[[context.production.plugins]]
package = "netlify-plugin-submit-sitemap"
