[build]
  base   ="build"
  publish="build/site"
  command="npm run build"

[[plugins]]
package = "@netlify/plugin-sitemap"

# submit sitemap must run after generate sitemap
[[context.production.plugins]]
package = "netlify-plugin-submit-sitemap
