name = 'me2christ'
pages_build_output_dir = 'build/site'

[vars]
NODE_ENV = 'production'
BUN_VERSION = '1.3.1'
YARN_VERSION = '1.22.22'
TURNSTILE_SITE_KEY = '0x4AAAAAAA2-A8XA2Z-Wu2IF'
WORKER_URL = 'https://me2christ-worker-prod.dizzib-dev.workers.dev'
